const express = require("express");
const router = express.Router();
const authMiddleware = require("../middleware/auth");

const {
  generateSchedule,
  // regenerateSchedule,
  getJadwalMingguan,
  // resolveScheduleConflict,
} = require("../controllers/schedule");

const {
  getJadwalKuliah,
  addJadwalKuliah,
  editJadwalKuliah,
  deleteJadwalKuliah,
} = require("../controllers/jadwalKuliah");

const {
  getJadwalMendatang,
  addJadwalMendatang,
  editJadwalMendatang,
  deleteJadwalMendatang,
  getJadwalMendatangHistory,
} = require("../controllers/jadwalMendatang");

const { getLastFormInput } = require("../controllers/schedule");

// Protect all routes
router.use(authMiddleware);

/*create schedule from openai for jadwal mingguan (Generate schedule from openai)
so when the user click "Generate Schedule" button, a form will be shown to the user to fill the schedule details, with textarea for the user to fill the schedule details, and a button to submit the form. (only generate and show preview to user, not save to database)
*/
router.post("/generate-schedule", generateSchedule);

/*regenerate schedule from openai for jadwal mingguan (Generate schedule from openai)
so when the user click "Regenerate Schedule" button, a form with existing details that user already filled when generate schedule the first timewill be shown so that user can edit add or delete the text within the same text area and a button to submit the form. (only generate and show preview to user, not save to database)
*/
// router.post("/regenerate-schedule", regenerateSchedule);

// get "Jadwal Mingguan" is the schedule that will be generated by openai after user confirm the save schedule button
router.get("/jadwal-mingguan", getJadwalMingguan);
router.get("/last-form-input", getLastFormInput);

// Jadwal Kuliah routes
router.get("/jadwal-kuliah", getJadwalKuliah);
router.post("/jadwal-kuliah", addJadwalKuliah);
router.put("/jadwal-kuliah/:kuliah_id", editJadwalKuliah);
router.delete("/jadwal-kuliah/:kuliah_id", deleteJadwalKuliah);

// Jadwal Mendatang routes
router.get("/jadwal-mendatang", getJadwalMendatang);
router.get("/jadwal-mendatang/history", getJadwalMendatangHistory);
router.post("/jadwal-mendatang", addJadwalMendatang);
router.put("/jadwal-mendatang/:id", editJadwalMendatang);
router.delete("/jadwal-mendatang/:id", deleteJadwalMendatang);

// // Resolve schedule conflict
// router.post("/resolve-schedule-conflict", resolveScheduleConflict);

module.exports = router;
